config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :books
  resources :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_one_attached :profile_picture
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  has_many_attached :cover_photos
  belongs_to :author

  validates :cover_photos, attached: true, content_type: "image/png", size: { less_than_or_equal_to: 1.megabytes, message: "should be less than 1 MB" }, aspect_ratio: :square
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :address, :profile_picture)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.author_id = params[:book][:author_id]
    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, cover_photos: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <h3><%= author.name %></h3>
  <hr>
  <p>
    <strong>Address:</strong>
    <%= author.address %>
  </p>
  <p class="d-flex flex-column">
    <strong>Profile Picture:</strong>
    <div>
      <%= image_tag author.profile_picture, size: "200x200" %>
    </div>
  </p>
  <hr>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div class="my-3">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_area :address %>
  </div>
  <div class="my-3">
    <%= form.label :profile_picture, style: "display: block" %>
    <%= form.file_field :profile_picture %>
  </div>
  <div class="my-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="mx-4 my-2">
  <h3 class="text-primary">Editing author</h3>
  <hr>
  <%= render "form", author: @author %>
  <hr>
  <br>
  <div>
    <%= link_to "Show this author", @author %> |
    <%= link_to "Back to authors", authors_path %>
  </div>
</div>

app/views/authors/index.html.erb
<div class="mx-4 my-2">
  <p style="color: green"><%= notice %></p>
  <h2>Authors</h2>
  <hr>
  <div id="authors">
    <% @authors.each_with_index do |author, index| %>
      <div class="mb-5">
        <div class="d-flex">
          <strong><%= index + 1 %> | Name :</strong>&nbsp;
          <p><%= author.name %></p>
        </div>
        <p>
          <%= link_to "Show this author", author, class:"bg-secondary text-white text-decoration-none fw-bold p-2 rounded" %>
        </p>
      </div>
    <% end %>
  </div>
  <hr>
  <%= link_to "New author", new_author_path, class:"bg-primary text-white text-decoration-none fw-bold p-2 rounded" %>
</div>

app/views/authors/new.html.erb
<div class="mx-4 my-2">
  <h3 class="text-primary">New author</h3>
  <hr>
  <%= render "form", author: @author %>
  <hr>
  <br>
  <div>
    <%= link_to "Back to authors", authors_path %>
  </div>
</div>

app/views/authors/show.html.erb
<div class="mx-4 my-2">
  <p style="color: green"><%= notice %></p>
  <%= render @author %>
  <div>
    <%= link_to "Edit this author", edit_author_path(@author), class:"bg-primary text-white text-decoration-none fw-bold p-2 rounded" %> |
    <%= link_to "Back to authors", authors_path, class:"bg-primary text-white text-decoration-none fw-bold p-2 rounded" %>
    <%= button_to "Destroy this author", @author, method: :delete, class:"bg-danger text-white text-decoration-none fw-bold p-1 rounded mt-3 border-0"  %>
  </div>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <h3><%= book.name %></h3>
  <hr>
  <p>
    <strong>Author Name:</strong>
    <%= Author.find(book.author_id).name %>
  </p>
  <p class="d-flex ">
    <strong>Cover Photos:</strong>
    <div class="d-flex w-100">
      <% book.cover_photos.each do |photo| %>
        <%= image_tag photo, size: "200x200", class:"mx-2" %>
      <% end %>
    </div>
  </p>
  <hr>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div class="my-3">
    <%= form.label :cover_photos, style: "display: block" %>
    <%= form.file_field :cover_photos, multiple: true %>
  </div>
  <div class="my-3">
    <%= form.label :author %>
    <%= form.collection_select :author_id, Author.all, :id, :name,  { prompt: "Select Author"} %>
  </div>
  <div class="my-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="mx-4 my-2">
  <h3 class="text-primary">Editing book</h3>
  <hr>
  <%= render "form", book: @book %>
  <hr>
  <br>
  <div>
    <%= link_to "Show this book", @book %> |
    <%= link_to "Back to books", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class="mx-4 my-2">
  <p style="color: green"><%= notice %></p>
  <h2>Books</h2>
  <hr>
  <div id="books">
    <% @books.each do |book| %>
      <div class="mb-5">
        <h4 class="text-primary"><%= book.name %></h4>
        <div class="d-flex">
          <strong>Author :</strong>&nbsp;
          <p><%= Author.find(book.author_id).name %></p>
        </div>
        <p>
          <%= link_to "Show this book", book, class:"bg-secondary text-white text-decoration-none fw-bold p-2 rounded" %>
        </p>
      </div>
    <% end %>
  </div>
  <hr>
  <%= link_to "New book", new_book_path, class:"bg-primary text-white text-decoration-none fw-bold p-2 rounded" %>
</div>

app/views/books/new.html.erb
<div class="mx-4 my-2">
  <h3 class="text-primary">New book</h3>
  <hr>
  <%= render "form", book: @book %>
  <hr>
  <br>
  <div>
    <%= link_to "Back to books", books_path %>
  </div>
</div>

app/views/books/show.html.erb
<div class="mx-4 my-2">
  <p style="color: green"><%= notice %></p>
  <%= render @book %>
  <div>
    <%= link_to "Edit this book", edit_book_path(@book), class:"bg-primary text-white text-decoration-none fw-bold p-2 rounded" %> |
    <%= link_to "Back to books", books_path, class:"bg-primary text-white text-decoration-none fw-bold p-2 rounded" %>
    <%= button_to "Destroy this book", @book, method: :delete, class:"bg-danger text-white text-decoration-none fw-bold p-1 rounded mt-3 border-0" %>
  </div>
</div>

app/views/home/index.html.erb
<h5 class="text-center m-5">Welcome!</h5>

app/views/layouts/_navbar.html.erb
<div class="d-flex bg-primary p-2 align-items-center justify-content-between">
  <%= link_to(root_path, class:"text-decoration-none") do%>
    <h3 class="text-white">My Library</h3>
  <% end %>
  <div>
    <%= link_to 'Books', books_path, class:"bg-white text-decoration-none fw-bold p-2 mx-2 rounded"%>
    <%= link_to 'Authors', authors_path, class:"bg-white text-decoration-none fw-bold p-2 mx-2 rounded"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>